import './globals.css'
import './icons.css'
import { ThemeProvider } from '@/globalComponents/services/Theme-Provider'
import { RobotoFont, Lobster } from './fonts/fonts'
// import React, { Suspense } from 'react'
import Loading from './Loading'
import Tanstack from '@/features/NewData/components/Tanstack'

export const metadata = {
  title: 'TBD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={` antialiased min-h-screen ${RobotoFont.variable} ${Lobster.variable}`}>
        <ThemeProvider attribute='class' defaultTheme={'dark'} disableTransitionOnChange={false}>
          <Tanstack>{children}</Tanstack>
        </ThemeProvider>
      </body>
    </html>
  )
}
